server:
  port: 8085
spring:
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      bootstrap-servers: localhost:9092
    dead_letter_topic: notification-retry
  datasource:
    url: jdbc:postgresql://localhost:33007/mini_project_db
    username: my_user
    password: my_password
#     url: jdbc:postgresql://8.219.131.180:8765/fintrack
#     username: root
#     password: P@SSWORD666
#    soccerdatehrd@gmail.com
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  #hibernate:
  #  jdbc:
  logging:
    level:
      com.levi.testhibernate: debug
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak-fintrack.sythorng.site/auth/realms/Fintrack
          jwk-set-uri: https://keycloak-fintrack.sythorng.site/auth/realms/Fintrack/protocol/openid-connect/certs
kafka:
  #  username: todo-username
  #  password: todo-password
  #  servers: ${KAFKA_SERVER:localhost:9092}
  #  idempotence: true
  #  acks: all
  #  maxInFlightReq: 5
  group-id: hero-consumer
  auto-offset: earliest
  #  mechanism: PLAIN
  #  protocol: SASL_PLAINTEXT
  topics:
    data: kb-email-service
Base:
  url: http://localhost:8088/api/v1/

smtp:
  username: soccerdatehrd@gmail.com
  password: tmkylzbkhzsautkz